import Head from "next/head";
import Define from "../components/Define";
import Faqs from "../components/Faqs";
import Intro from "../components/Intro";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div className="w-full flex items-center justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-[90vw] my-[5vh]">
        <Navbar />
        <Intro />
        <Define />
        <Faqs />
      </div>
    </div>
  );
}
